In [164]:
import pandas as pd
import numpy as npd

In [165]:
df_udemy = pd.read_csv('web_scrapping/Datasets/udemy_courses.csv')

In [166]:
df_udemy.head()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3.0,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13T14:57:18Z,Business Finance

In [167]:
df_udemy.drop(['course_id','price','num_subscribers','num_reviews','num_lectures'],axis=1,inplace =True)

In [168]:
df_udemy.head()

,course_title,url,is_paid,level,content_duration,published_timestamp,subject
0,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance
2,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,All Levels,3.0,2017-05-30T20:07:24Z,Business Finance
4,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,Intermediate Level,2.0,2016-12-13T14:57:18Z,Business Finance

In [169]:
df_udemy.rename(columns = {'is_paid':'certification', 'subject':'organization'}, inplace = True) 
df_udemy.drop(['published_timestamp'],axis=1,inplace =True)

In [170]:
df_udemy.drop(['content_duration'],axis=1,inplace =True)
df_udemy.head()

,course_title,url,certification,level,organization
0,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,All Levels,Business Finance
1,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,All Levels,Business Finance
2,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,Intermediate Level,Business Finance
3,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,All Levels,Business Finance
4,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,Intermediate Level,Business Finance

In [171]:
df_udemy['platform']='udemy'

In [172]:
booleandf = df_udemy.select_dtypes(include=[bool])
booleanDictionary = {True: 'COURSE', False: 'FREE'}

for column in booleandf:
    df_udemy['certification'] = df_udemy['certification'].map(booleanDictionary)

In [173]:
df_udemy.head()

,course_title,url,certification,level,organization,platform
0,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,COURSE,All Levels,Business Finance,udemy
1,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,COURSE,All Levels,Business Finance,udemy
2,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,COURSE,Intermediate Level,Business Finance,udemy
3,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,COURSE,All Levels,Business Finance,udemy
4,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,COURSE,Intermediate Level,Business Finance,udemy

In [174]:
df_udacity = pd.read_csv('web_scrapping/Datasets/udacity_Courses.csv')

In [175]:
df_udacity.columns

Index(['Unnamed: 0', 'course_title', 'course_organization',
       'course_Certificate_type', 'courses_url', 'course_difficulty'],
      dtype='object')

In [176]:
df_udacity.certification.unique()

AttributeError: 'DataFrame' object has no attribute 'certification'

In [177]:
df_udacity.drop(['Unnamed: 0'],axis=1,inplace =True)

In [178]:
df_udacity.rename(columns = {'course_organization':'organization', 'courses_url':'url','course_difficulty':'level','course_Certificate_type':'certification'}, inplace = True)

In [179]:
df_udacity.head()

,course_title,organization,certification,url,level
0,A/B Testing,School of Programming,Free,https://www.udacity.com/course/course/what-is-...,beginner
1,AI Product Manager,School of Artificial Intelligence,Free,https://www.udacity.com/course/course/what-is-...,intermediate
2,AI Programming with Python,School of Artificial Intelligence,Free,https://www.udacity.com/course/course/what-is-...,intermediate
3,AI for Business Leaders,School of Business,Free,https://www.udacity.com/course/course/what-is-...,advanced
4,AI for Healthcare,School of Artificial Intelligence,Free,https://www.udacity.com/course/course/what-is-...,intermediate

In [180]:
df_coursera = pd.read_csv('web_scrapping/Datasets/UCoursera_Courses.csv')

In [181]:
df_coursera.head()

,Unnamed: 0,course_title,course_organization,course_Certificate_type,course_rating,course_difficulty,course_students_enrolled
0,134,(ISC)² Systems Security Certified Practitioner...,(ISC)²,SPECIALIZATION,4.7,Beginner,5.3k
1,743,A Crash Course in Causality: Inferring Causal...,University of Pennsylvania,COURSE,4.7,Intermediate,17k
2,874,A Crash Course in Data Science,Johns Hopkins University,COURSE,4.5,Mixed,130k
3,413,A Law Student's Toolkit,Yale University,COURSE,4.7,Mixed,91k
4,635,A Life of Happiness and Fulfillment,Indian School of Business,COURSE,4.8,Mixed,320k

In [182]:
df_coursera.columns

Index(['Unnamed: 0', 'course_title', 'course_organization',
       'course_Certificate_type', 'course_rating', 'course_difficulty',
       'course_students_enrolled'],
      dtype='object')

In [183]:
df_coursera.drop(['Unnamed: 0','course_rating','course_students_enrolled'],axis=1,inplace =True)

In [184]:
df_coursera.rename(columns = {'course_organization':'organization', 'course_difficulty':'level','course_Certificate_type':'certification'}, inplace = True)

In [185]:
df_coursera.head()

,course_title,organization,certification,level
0,(ISC)² Systems Security Certified Practitioner...,(ISC)²,SPECIALIZATION,Beginner
1,A Crash Course in Causality: Inferring Causal...,University of Pennsylvania,COURSE,Intermediate
2,A Crash Course in Data Science,Johns Hopkins University,COURSE,Mixed
3,A Law Student's Toolkit,Yale University,COURSE,Mixed
4,A Life of Happiness and Fulfillment,Indian School of Business,COURSE,Mixed

In [186]:
df_pluralsight = pd.read_csv('web_scrapping/Datasets/pluralsight_Courses.csv')

In [187]:
df_pluralsight.head()

,Unnamed: 0,course_title,course_link,course_level
0,55,AWS Networking Deep Dive: Virtual Private Clou...,/courses/aws-networking-deep-dive-vpc,Intermediate
1,7,Accelerated Introduction to C++,/courses/accelerated-introduction-cpp,Advanced
2,84,Advanced Machine Learning with ENCOG,/courses/advanced-machine-learning-encog,Advanced
3,67,Advanced Machine Learning with ENCOG - Part 2,/courses/advanced-machine-learning-encog-pt2,Advanced
4,149,Advanced Network Security on AWS,/courses/advanced-networking-security-aws,Advanced

In [188]:
df_pluralsight.drop(['Unnamed: 0'],axis=1,inplace =True)

In [189]:
df_pluralsight.rename(columns = { 'course_level':'level','course_link':'url'}, inplace = True)

In [190]:
df_pluralsight['organization'] = 'pluralsight'

In [191]:
df_pluralsight.head()

,course_title,url,level,organization
0,AWS Networking Deep Dive: Virtual Private Clou...,/courses/aws-networking-deep-dive-vpc,Intermediate,pluralsight
1,Accelerated Introduction to C++,/courses/accelerated-introduction-cpp,Advanced,pluralsight
2,Advanced Machine Learning with ENCOG,/courses/advanced-machine-learning-encog,Advanced,pluralsight
3,Advanced Machine Learning with ENCOG - Part 2,/courses/advanced-machine-learning-encog-pt2,Advanced,pluralsight
4,Advanced Network Security on AWS,/courses/advanced-networking-security-aws,Advanced,pluralsight

In [192]:
df_pluralsight['url'] = 'https://www.pluralsight.com' + df_pluralsight['url'].astype(str)

In [193]:
df_pluralsight['certification'] = 'COURSE'

In [194]:
df_udacity['platform']='udacity'
df_coursera['platform']='coursera'
df_pluralsight['platform']='pluralsight'

In [195]:
df_coursera['url'] = 'https://www.coursera.org/search?query=' +df_coursera['course_title'].astype(str)+ '&'

In [196]:
df_coursera.head()

,course_title,organization,certification,level,platform,url
0,(ISC)² Systems Security Certified Practitioner...,(ISC)²,SPECIALIZATION,Beginner,coursera,https://www.coursera.org/search?query=(ISC)² S...
1,A Crash Course in Causality: Inferring Causal...,University of Pennsylvania,COURSE,Intermediate,coursera,https://www.coursera.org/search?query=A Crash ...
2,A Crash Course in Data Science,Johns Hopkins University,COURSE,Mixed,coursera,https://www.coursera.org/search?query=A Crash ...
3,A Law Student's Toolkit,Yale University,COURSE,Mixed,coursera,https://www.coursera.org/search?query=A Law St...
4,A Life of Happiness and Fulfillment,Indian School of Business,COURSE,Mixed,coursera,https://www.coursera.org/search?query=A Life o...

In [197]:
df_coursera.certification.unique()

array(['SPECIALIZATION', 'COURSE', 'PROFESSIONAL CERTIFICATE'],
      dtype=object)

In [198]:
df_udemy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3678 entries, 0 to 3677
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   course_title   3678 non-null   object
 1   url            3678 non-null   object
 2   certification  3678 non-null   object
 3   level          3678 non-null   object
 4   organization   3678 non-null   object
 5   platform       3678 non-null   object
dtypes: object(6)
memory usage: 172.5+ KB

In [199]:
df_udemy

,course_title,url,certification,level,organization,platform
0,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,COURSE,All Levels,Business Finance,udemy
1,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,COURSE,All Levels,Business Finance,udemy
2,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,COURSE,Intermediate Level,Business Finance,udemy
3,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,COURSE,All Levels,Business Finance,udemy
4,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,COURSE,Intermediate Level,Business Finance,udemy
...,...,...,...,...,...,...
3673,Learn jQuery from Scratch - Master of JavaScri...,https://www.udemy.com/easy-jquery-for-beginner...,COURSE,All Levels,Web Development,udemy
3674,How To Design A WordPress Website With No Codi...,https://www.udemy.com/how-to-make-a-wordpress-...,COURSE,Beginner Level,Web Development,udemy
3675,Learn and Build using Polymer,https://www.udemy.com/learn-and-build-using-po...,COURSE,All Levels,Web Development,udemy
3676,CSS Animations: Create Amazing Effects on Your...,https://www.udemy.com/css-animations-create-am...,COURSE,All Levels,Web Development,udemy
3677,Using MODX CMS to Build Websites: A Beginner's...,https://www.udemy.com/using-modx-cms-to-build-...,COURSE,Beginner Level,Web Development,udemy

In [200]:
frames = [df_udemy,df_udacity, df_coursera, df_pluralsight]
df = pd.concat(frames)

In [201]:
df.head()

,course_title,url,certification,level,organization,platform
0,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,COURSE,All Levels,Business Finance,udemy
1,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,COURSE,All Levels,Business Finance,udemy
2,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,COURSE,Intermediate Level,Business Finance,udemy
3,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,COURSE,All Levels,Business Finance,udemy
4,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,COURSE,Intermediate Level,Business Finance,udemy

In [202]:
print(df_udemy.columns)
print(df_coursera.columns)
print(df_udacity.columns)
print(df_pluralsight.columns)

Index(['course_title', 'url', 'certification', 'level', 'organization',
       'platform'],
      dtype='object')
Index(['course_title', 'organization', 'certification', 'level', 'platform',
       'url'],
      dtype='object')
Index(['course_title', 'organization', 'certification', 'url', 'level',
       'platform'],
      dtype='object')
Index(['course_title', 'url', 'level', 'organization', 'certification',
       'platform'],
      dtype='object')

In [203]:
df

,course_title,url,certification,level,organization,platform
0,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,COURSE,All Levels,Business Finance,udemy
1,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,COURSE,All Levels,Business Finance,udemy
2,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,COURSE,Intermediate Level,Business Finance,udemy
3,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,COURSE,All Levels,Business Finance,udemy
4,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,COURSE,Intermediate Level,Business Finance,udemy
...,...,...,...,...,...,...
175,Windows Performance Monitoring Fundamentals,https://www.pluralsight.com/courses/windows-pe...,COURSE,Beginner,pluralsight,pluralsight
176,Windows PowerShell Toolmaking Fundamentals,https://www.pluralsight.com/courses/powershell...,COURSE,Intermediate,pluralsight,pluralsight
177,Windows Server 2012 R2 (70-413) Server Deployment,https://www.pluralsight.com/courses/windows-se...,COURSE,Intermediate,pluralsight,pluralsight
178,Windows Server Administration Fundamentals Usi...,https://www.pluralsight.com/courses/windows-se...,COURSE,Beginner,pluralsight,pluralsight
179,Working With Temporal Data in SQL Server,https://www.pluralsight.com/courses/working-wi...,COURSE,Intermediate,pluralsight,pluralsight

In [205]:
df.isnull().sum()

course_title     0
url              0
certification    0
level            0
organization     0
platform         0
dtype: int64